Ecrtest 3 (#10)
* update dockerfile for test

* make architecture easier to manage

* attempt without arch file

Also, cleanup and expand the summary output

diff --git a/.github/workflows/dev-build.yml b/.github/workflows/dev-build.yml
--- a/.github/workflows/dev-build.yml
+++ b/.github/workflows/dev-build.yml
@@ -16,7 +16,34 @@ permissions:
   contents: read
 
 jobs:
+  prep:
+    runs-on: ubuntu-latest
+    outputs: 
+      cpuarch: ${{ steps.setarch.outputs.cpuarch }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v5
+
+      - name: Set CPU Architecture
+        id: setarch
+        run: |
+          echo "### Architecture Selection" >> $GITHUB_STEP_SUMMARY
+          if [[ -f .aws-architecture ]]; then
+            ARCH=$(cat .aws-architecture)
+            echo "\`$ARCH\` was read from \`.aws-architecture\` and passed to the deploy job." >> $GITHUB_STEP_SUMMARY
+          else
+            ARCH="linux/amd64"
+            echo "No \`.aws-architecture\` file, so default \`$ARCH\` was passed to the deploy job." >> $GITHUB_STEP_SUMMARY
+          fi
+          if [[ "$ARCH" != "linux/arm64" && "$ARCH" != "linux/amd64" ]]; then
+            echo "$ARCH is INVALID architecture!"
+            echo "$ARCH is INVALID architecture!" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          echo "cpuarch=$ARCH" >> $GITHUB_OUTPUT
+
   deploy:
+    needs: prep
     name: Dev Container Deploy
     uses: mitlibraries/.github/.github/workflows/ecr-multi-arch-deploy-dev.yml@multi-arch-deploy
     secrets: inherit
@@ -24,6 +51,6 @@ jobs:
       AWS_REGION: "us-east-1"
       GHA_ROLE: "ecr-workflow-test-gha-dev"
       ECR: "ecr-workflow-test-dev"
-      CPU_ARCH: "linux/arm64"
+      CPU_ARCH: ${{ needs.prep.outputs.cpuarch }}
       # FUNCTION: ""
       # PREBUILD: 
