Updated workflows
This includes updates to both the dev and
stage workflows.

fix emojis

update production caller

New Dockerfile

diff --git a/.github/workflows/prod-promote.yml b/.github/workflows/prod-promote.yml
--- a/.github/workflows/prod-promote.yml
+++ b/.github/workflows/prod-promote.yml
@@ -11,8 +11,36 @@ permissions:
   contents: read
 
 jobs:
+  prep:
+    name: Prep for Promote
+    runs-on: ubuntu-latest
+    outputs: 
+      cpuarch: ${{ steps.setarch.outputs.cpuarch }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v5
+
+      - name: Set CPU Architecture
+        id: setarch
+        run: |
+          echo "### :abacus: Architecture Selection" >> $GITHUB_STEP_SUMMARY
+          if [[ -f .aws-architecture ]]; then
+            ARCH=$(cat .aws-architecture)
+            echo "\`$ARCH\` was read from \`.aws-architecture\` and passed to the deploy job." >> $GITHUB_STEP_SUMMARY
+          else
+            ARCH="linux/amd64"
+            echo "No \`.aws-architecture\` file, so default \`$ARCH\` was passed to the deploy job." >> $GITHUB_STEP_SUMMARY
+          fi
+          if [[ "$ARCH" != "linux/arm64" && "$ARCH" != "linux/amd64" ]]; then
+            echo "$ARCH is INVALID architecture!"
+            echo "$ARCH is INVALID architecture!" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          echo "cpuarch=$ARCH" >> $GITHUB_OUTPUT
+
   deploy:
-    name: Prod Container Promote
+    needs: prep
+    name: Deploy
     uses: mitlibraries/.github/.github/workflows/ecr-multi-arch-promote-prod.yml@multi-arch-deploy
     secrets: inherit
     with:
@@ -21,5 +49,6 @@ jobs:
       GHA_ROLE_PROD: ecr-workflow-test-gha-prod
       ECR_STAGE: "ecr-workflow-test-stage"
       ECR_PROD: "ecr-workflow-test-prod"
+      CPU_ARCH: ${{ needs.prep.outputs.cpuarch }}
       # FUNCTION: ""
  
